### PR TITLE
util.sh: Disable verboseness temporarily

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
Care to comment why or just really tmp?

**Comment by leandro-lucarella-sociomantic** [comment]
It's just too noisy to print every little detail about how the version is obtained, that's all. I will clarify in the commit.

**Comment by leandro-lucarella-sociomantic** [comment]
Updated!

**Comment by leandro-lucarella-sociomantic** [comment]
Or not. I don't get it, the force-push says I did but GitHub keeps showing the old commit.

**Comment by leandro-lucarella-sociomantic** [comment]
Mmmm, GitHub is orange... Maybe that's why.

**Pull request merged**
