### PR TITLE
Several fixes for last-version

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
Fix a few issues with last-version (in particular what was observed in #12) and also improves the testing for it.

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
OK, with this I will try a `rc2`.

**Comment by leandro-lucarella-sociomantic** [comment]
Oh, this is nice, now we are core-dumping `apt`:
```
+ apt-get -y install libebtree6=6.0.socio6-trusty libebtree6-dbg=6.0.socio6-trusty libebtree6-dev=6.0.socio6-trusty dmd1=1.080.0-trusty libtangort-dmd-dev=1.7.0-trusty dmd-transitional=2.070.2.s11-trusty  dmd-bin=2.070.2-0 libphobos2-dev=2.070.2-0
Reading package lists...
Building dependency tree...
Reading state information...
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::compare
Aborted (core dumped)
```

**Comment by leandro-lucarella-sociomantic** [comment]
Arrrgh! Trusty still fails with an apt core dump, it works for me locally...

**Comment by leandro-lucarella-sociomantic** [comment]
I contacted Travis support, I have no idea what to do here, it just works perfectly locally...

**Comment by mihails-strasuns-sociomantic** [comment]
Fails to me too when I run `make all` from Arch Linux host with docker 17.05.0

```
+ apt-get -y install libebtree6=6.0.socio6-trusty libebtree6-dbg=6.0.socio6-trusty libebtree6-dev=6.0.socio6-trusty dmd1=1.080.0-trusty libtangort-dmd-dev=1.7.0-trusty dmd-transitional=2.070.2.s12-trusty  dmd-bin=2.070.2-0 libphobos2-dev=2.070.2-0
Reading package lists...
Building dependency tree...
Reading state information...
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::compare
Aborted (core dumped)
```

**Comment by nemanja-boric-sociomantic** [comment]
Workaround:

```
#!/bin/sh
set -xeu

# Get utility stuff
. ./util.sh

apt-get update
packages=""$(apt_ver libebtree6 "$VERSION_EBTREE")" \
	"$(apt_ver libebtree6-dbg "$VERSION_EBTREE")" \
	"$(apt_ver libebtree6-dev "$VERSION_EBTREE")" \
	"$(apt_ver dmd1 "$VERSION_DMD1")" \
	"$(apt_ver libtangort-dmd-dev "$VERSION_TANGORT")" \
	"$(apt_ver dmd-transitional "$VERSION_DMD_TRANSITIONAL")" \
	"$(apt_ver d1to2fix "$VERSION_D1TO2FIX")" \
	"$(apt_ver dmd-bin "$VERSION_DMD")" \
	"$(apt_ver libphobos2-dev "$VERSION_DMD")""

apt-get -y install $packages

# Remove common temporary files and packages
cleanup

```

**Comment by nemanja-boric-sociomantic** [comment]
It seems to be something relating `d1to2fix` not being resolved by `apt_ver`:

```
root@07250c969e63:/docker-tmp# cat ./dlang 
#!/bin/sh
set -xeu

# Get utility stuff
. ./util.sh

apt-get update

apt-get -y install "$(apt_ver libebtree6 "$VERSION_EBTREE")" \
	"$(apt_ver libebtree6-dbg "$VERSION_EBTREE")" \
	"$(apt_ver libebtree6-dev "$VERSION_EBTREE")" \
	"$(apt_ver dmd1 "$VERSION_DMD1")" \
	"$(apt_ver libtangort-dmd-dev "$VERSION_TANGORT")" \
	"$(apt_ver dmd-transitional "$VERSION_DMD_TRANSITIONAL")" \
	"$(apt_ver dmd-bin "$VERSION_DMD")" \
	"$(apt_ver libphobos2-dev "$VERSION_DMD")"
	#"$(apt_ver d1to2fix "$VERSION_D1TO2FIX")" \

# Remove common temporary files and packages
cleanup
```

**Comment by nemanja-boric-sociomantic** [comment]
Simple reproducible case:

```
root@07250c969e63:/docker-tmp# apt-get install ""
Reading package lists... Done
Building dependency tree       
Reading state information... Done
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::compare
Aborted (core dumped)
```

**Comment by nemanja-boric-sociomantic** [comment]
Seems like apt-get doesn't care about empty argument.

**Comment by nemanja-boric-sociomantic** [comment]
This seems to be an issue in trusty's apt-get:

```
root@78c915e30316:/# lsb_release -cs
trusty
root@78c915e30316:/# apt-get --version
apt 1.0.1ubuntu2 for amd64 compiled on Jan 12 2016 20:13:58
Supported modules:
*Ver: Standard .deb
*Pkg:  Debian dpkg interface (Priority 30)
 Pkg:  Debian APT solver interface (Priority -1000)
 S.L: 'deb' Standard Debian binary tree
 S.L: 'deb-src' Standard Debian source tree
 Idx: Debian Source Index
 Idx: Debian Package Index
 Idx: Debian Translation Index
 Idx: Debian dpkg status file
 Idx: EDSP scenario file
root@78c915e30316:/# apt-get install ""
Reading package lists... Done
Building dependency tree       
Reading state information... Done
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::compare
Aborted (core dumped)
```

and Xenial:
```
root@45f3dec2f311:/# apt-get --version
apt 1.2.20 (amd64)
Supported modules:
*Ver: Standard .deb
*Pkg:  Debian dpkg interface (Priority 30)
 Pkg:  Debian APT solver interface (Priority -1000)
 S.L: 'deb' Debian binary tree
 S.L: 'deb-src' Debian source tree
 Idx: Debian Source Index
 Idx: Debian Package Index
 Idx: Debian Translation Index
 Idx: Debian dpkg status file
 Idx: Debian deb file
 Idx: Debian dsc file
 Idx: Debian control file
 Idx: EDSP scenario file
root@45f3dec2f311:/# apt-get install ""
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by nemanja-boric-sociomantic** [comment]
Found a bug in the debian bug tracker: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=744940

**Comment by nemanja-boric-sociomantic** [comment]
Ubuntu tracker bug: https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1218308
https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1352565

**Comment by nemanja-boric-sociomantic** [comment]
Btw, the problem is caused because `VERSION_D1TO2FIX=v0.9.x`. It should be `VERSION_D1TO2FIX=0.9.x` (no leading `v` in debian packages)

**Comment by leandro-lucarella-sociomantic** [comment]
Thanks, it should fail though, I will investigate after I finish with #13 .

**Comment by leandro-lucarella-sociomantic** [comment]
OK, I added the fixes to jfrog checksum checking and some more testing by at least calling the installing tools (and another fix to `util.sh` to make sure it fails if a version can't be found, this is why the problem with d1to2fix version being wrong didn't show up).

If this passes we should be fine for v2.0.0.

Please re-review if you can, but I will do the merge after all checks pass, I'm testing locally too, just in case :)

**Comment by leandro-lucarella-sociomantic** [comment]
BTW, thanks a lot @nemanja-boric-sociomantic for the investigations on why `apt-get` failed!

**Comment by leandro-lucarella-sociomantic** [comment]
:green_heart:

**Comment by nemanja-boric-sociomantic** [comment]
:green_heart:

**Comment by leandro-lucarella-sociomantic** [comment]
OK, I'll merge.

**Comment by leandro-lucarella-sociomantic** [comment]
v2.0.0-rc2 tagged, let's see how the projects using `v2-test` go.

**Pull request merged**
