### PR TITLE
Update copyright owner

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
This should probably go to v4.1.x

**Comment by leandro-lucarella-sociomantic** [comment]
Yeah, changed, after merging to v4.x.x, v5.0.x, v5.x.x and v6.x.x we should check no new files were added with the old copyright.

**Comment by leandro-lucarella-sociomantic** [comment]
Actually, since I did it originally for v5.x.x it should apply without problems to all v4, v5 and v6 (since v6 was created recently, nothing was added yet there).

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

**Comment by leandro-lucarella-sociomantic** [comment]
OK, I'll do the chain release on Monday so we propagate this to other branches.

**Pull request merged**
