### PR TITLE
Bump tangort version to v1.8.* and dmd version to v2.078.*

### LINKED ISSUE #43: Update dmd in docker Image
Currently dmd is on `2.070.2` which is at this point over one year old,
We should update to the latest release which ocean can use. (`2.077`) at this point.
@leandro-lucarella-sociomantic, @mihails-strasuns-sociomantic

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
Fixes #43.

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
My idea is to release v4 after this is merged, or is it anything else that we want to push for v4?

**Comment by leandro-lucarella-sociomantic** [comment]
Mmm, failing because there is still no dmd v2.078.0 in d-apt...

**Comment by mathias-lang-sociomantic** [comment]
You mean v2.078 ?
Maybe just use v2.077 ? :P

**Comment by leandro-lucarella-sociomantic** [comment]
We have no rush to release v4, and I prefer to include v1.078.0 as we need it for coverage report merging.

**Comment by mihails-strasuns-sociomantic** [comment]
We need to upgrade our tsunami projects (ocean, swarm etc) to 2.078 first in that case, just to be extra sure there are no surprises. That alone can be a good enough reason to stick to 2.077 by default for v4.

**Comment by leandro-lucarella-sociomantic** [comment]
If it compiles and pass tests it should work. I think we can take a bit of risk with this, D2 support is still not considered *stable* and the update is opt-in anyway, so I would strongly prefer to include v2.078.0 in v4, so we can start working on the coverage merging support with it, and projects that are happy with v2.078.0 can already move to v4.

**Comment by mihails-strasuns-sociomantic** [comment]
> If it compiles and pass tests it should work. 

We don't know that yet. This version is not even available in d-apt yet, it was released few days ago.

**Comment by leandro-lucarella-sociomantic** [comment]
I don't think there is a rush for v4 either, it could be released in a week or two :)

**Comment by stefan-koch-sociomantic** [comment]
I would rather go with v2.077 (honestly v2.072 is even more preferred :))

**Review by stefan-koch-sociomantic — APPROVED** [review]
I think it makes sense to have the default compiler be a fairly modern one.

**Comment by nemanja-boric-sociomantic** [comment]
The wildcard makes it easy, otherwise I would wait for `2.078.1`.

**Comment by mihails-strasuns-sociomantic** [comment]
Ocean was upgraded to 2.078 few days ago. It was fine, but there was one rather annoying new deprecation - https://github.com/sociomantic-tsunami/ocean/pull/428

**Comment by leandro-lucarella-sociomantic** [comment]
Restarting the build as now 2.078 is in d-apt.

**Comment by leandro-lucarella-sociomantic** [comment]
Is green now. But I guess we should wait until tango gets the debian package version fixed.

**Comment by leandro-lucarella-sociomantic** [comment]
tangort version fixed. I guess we are ready for this since also ocean is already running tests with v2.078?

Re-running test now.

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

**Review by mathias-lang-sociomantic — APPROVED** [review]

**Review by nemanja-boric-sociomantic — APPROVED** [review]

**Pull request merged**
