### PR TITLE
Add dumb-init binary to runtimebase image.

### PR DESCRIPTION
**Pull request by camilo-schoeningh-sociomantic**
As we preparing containers to run in Kubernetes and want them to handle
signals better.

Refs #66

### CODE REVIEW

**Review by mihails-strasuns — COMMENTED** [review]
You also need to set it as `ENTRYPOINT` for the image.

**Review by mateusz-gozdek-sociomantic — APPROVED** [review]

**Comment by mateusz-gozdek-sociomantic** [comment]
And why not https://github.com/krallin/tini ?

**Comment by nemanja-boric-sociomantic** [comment]
> NOTE: If you are using Docker 1.13 or greater, Tini is included in Docker itself. This includes all versions of Docker CE. To enable Tini, just pass the --init flag to docker run.

**Comment by nemanja-boric-sociomantic** [comment]
I think we all agreed on tini.

**Comment by mihails-strasuns** [comment]
@camilo-schoeningh-sociomantic has mentioned that benefit of dumb-init that is relevant to k8s is that it allows overriding signals.

**Comment by mihails-strasuns** [comment]
FYI: I will get tot testing this tomorrow most likely

**Comment by camilo-schoeningh-sociomantic** [comment]
@mateusz-gozdek-sociomantic  This is written in the Issue.. But mostly because dump-init supports signal rewriting.

**Review by mihails-strasuns — APPROVED** [review]
Tested with dhtnode, works as expected.

**Comment by mihails-strasuns** [comment]
Needs release notes but I will add those myself.

**Comment by maria-gomez-sociomantic** [comment]
Hello,

I am not sure this mention is meant to be for me.

Cheers,

María
María Gómez Llamazares · Senior Technical Account Manager

S mgomezllamazares

T +34 91 565 42 30  · M +34 620 50 61 25

sociomantic.com <https://www.sociomantic.com/?utm_source=sociomantic&utm_medium=email&utm_campaign=signature-homepage>  · Twitter <https://www.twitter.com/@sociomantic>  · Facebook <https://facebook.com/sociomantic>  · Newsletter <https://sociomantic.us2.list-manage.com/subscribe?u=071562b92b11edd456ae44134&id=b94ab6eee4>  · Careers<https://www.sociomantic.com/careers/?utm_source=sociomantic&utm_medium=email&utm_campaign=signature-careers>



[SOCIOMANTIC from dunnhumby]



This message and any attachments are confidential and intended solely for the use of the individual to whom it is addressed.

**Pull request merged**
