### PR TITLE
Add llucax (myself) to the FUNDING.yml file

### PR DESCRIPTION
**Pull request by llucax**

### CODE REVIEW

**Review by ibuclaw — APPROVED** [review]

**Comment by ibuclaw** [comment]
Ignoring "mysefl". :-)

**Comment by daniel-zullo** [comment]
There are 2 commits that are not related to the changes for funding. Maybe the PR needs rebasing?

**Comment by llucax** [comment]
Woops! Good catch! I'll update.

**Comment by llucax** [comment]
The problem seems to be the default branch wasn't updated after releasing v8.0.0 (it is still at v7.x.x and I based this PR in v8.x.x. Should we update the default branch to v8.x.x?

**Comment by daniel-zullo** [comment]
Right, that was the problem. I have already updated v8.x.x as the default branch

**Comment by daniel-zullo** [comment]
It seems there is an issue with the version of ruby for ubuntu xenial now

`gem_ver travis 1.8.x` requires `Ruby version >= 2.4.0`

**Comment by daniel-zullo** [comment]
`gem install --version=1.8.10 travis` works for ubuntu xenial and
`gem install --version=1.8.13 travis` doesn't.

We would probably need to set the specific version of travis that works for xenial rather than taking the latest on v1.8.x

**Comment by llucax** [comment]
> It seems there is an issue with the version of ruby for ubuntu xenial now

Yeah, I was just looking at that.

> `gem install --version=1.8.10 travis` works for ubuntu xenial and

Good second catch, I was looking if ruby2.4 is installable in xenial but not out of the box, so I guess it makes more sense to fix travis to 1.8.10 for now, until xenial support is removed (which I guess it shouldn't be too far as the end of support is on April 2021).

**Comment by llucax** [comment]
Added commit to fix travis version to 1.8.10 for xenial.

**Review by daniel-zullo — APPROVED** [review]
LGTM

**Comment by llucax** [comment]
It didn't work, still complaining about needing ruby2.4 :cry:

**Comment by llucax** [comment]
Looking at old successful build logs, as you point out, travis 1.8.10 was [built successfully](https://travis-ci.org/github/sociomantic-tsunami/cachalot/jobs/599719587#L1857), but at that time, launchy was retrieved at version 2.4.3. Now launchy 2.5.0 is being downloaded, and it requires ruby2.4. I think launchy people fucked up the dependencies and made an unintentional breaking change in a minor release :unamused:

**Comment by llucax** [comment]
I don't have very high hopes on this being fixed, so maybe we should start thinking about an alternative plan (I can only think of looking for a ruby2.4 PPA for xenial or removing xenial).

https://github.com/copiousfreetime/launchy/issues/139

**Comment by daniel-zullo** [comment]
ohh that sucks. Sorry I didn't spot that

Anyway I think it is not worth the effort of looking for and setting a ruby PPA for xenial as xenial is running out of support in ~5 months (April/2021 as stated above). I am leaning towards to drop support for xenial but it is also fine with me if you really want to go with the PPA workaround.

**Comment by llucax** [comment]
Yeah, I agree, let's give launchy some time to see how they respond and if nothing happens we remove xenial and that's it.

**Comment by llucax** [comment]
As expected, radio silence... So #90

**Comment by daniel-zullo** [comment]
This is now ready to go as support for xenial has been removed in #90

**Pull request merged**
