### PR TITLE
Upgrade jfrog to 1.17.1

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**

### CODE REVIEW

**Review by mihails-strasuns — COMMENTED** [review]
Changelog in comment? :P

**Comment by leandro-lucarella-sociomantic** [comment]
> Changelog in comment? :P

What?

**Comment by mihails-strasuns** [comment]
You have updated jfrog. There must be some changes that brings - would be nice to at least copy link to changelog into commit message.

**Comment by leandro-lucarella-sociomantic** [comment]
Ah, we never did that before, but we could start... Updated!

**Comment by leandro-lucarella-sociomantic** [comment]
Ping? Last missing part of initial v6 release for `develbase:bionic-v6`.

**Review by mihails-strasuns — APPROVED** [review]

**Pull request merged**
