### PR TITLE
Update almost all tools and libs versions

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
This would be v5.0.0 release.

**Comment by leandro-lucarella-sociomantic** [comment]
Damn bintray: `E: Failed to fetch https://dl.bintray.com/sociomantic-tsunami/dlang/dists/xenial/prerelease/binary-amd64/Packages  Writing more data than expected (7878 > 7587)`

**Comment by leandro-lucarella-sociomantic** [comment]
For the records, I [triggered a metadate rebuild in bintray](https://blog.bintray.com/2014/12/16/hosting-debian-packages-on-bintray-rocks/) and it seems like that fixed it.

But now shit got real:
```
+ dmd1 -run /tmp/x.d
/usr/include/d1/object.d(46): Error: module string is in file 'rt/util/string.d' which cannot be read
import path[0] = /usr/include/d1
Makefile:86: recipe for target 'test-dlang.xenial' failed
make: *** [test-dlang.xenial] Error 1
+ cat /tmp/x.d
void main() {}
```
Any ideas @mihails-strasuns-sociomantic  ?

**Comment by leandro-lucarella-sociomantic** [comment]
There is no `/usr/include/d1/rt` at all :thinking:

**Comment by nemanja-boric-sociomantic** [comment]
I suspect this is the culprit: https://github.com/sociomantic-tsunami/tangort/commit/96ffc2fdf763076ab0140dc947f856337f2764af#diff-78098622ac9616647a4c80637a2036c4R57 :-)

```diff
-src := $(call find_files,.[dcS],,$C/src/rt) \
-	$(call find_files,.[dcS],,$C/src/gc/$(D_GC)) \
-	$(call find_files,.[dcS],,$C/src/core)
+src := $(call find_files,.[dcS],,$C/src)
 ```

**Comment by leandro-lucarella-sociomantic** [comment]
Yeah, I have the same feeling, but I don't understand why. The `rt` package should not be exposed publicly, right? I guess now the compiler wants to actually compile `object.d` each time you compile something... Maybe we need to generate the `object.di` and ship that instead of the `object.d`.

Old working package:
```console
$ ls /usr/include/d1/
core  object.di  std
```

New faulty package:
```console
cachalot@e1008d4cab09:~$ ls /usr/include/d1/
core  object.d	std
```

**Comment by leandro-lucarella-sociomantic** [comment]
To be honest, I would just revert that change, is not worth the trouble for something that will dies soon enough...

**Comment by nemanja-boric-sociomantic** [comment]
Yeah, `object.d` includes bits of runtime: 

https://github.com/sociomantic-tsunami/tangort/blob/96ffc2fdf763076ab0140dc947f856337f2764af/src/object.d#L40-L51

while object.di didn't use to do that.

**Comment by leandro-lucarella-sociomantic** [comment]
https://github.com/sociomantic-tsunami/tangort/pull/35

**Comment by mihails-strasuns-sociomantic** [comment]
Yeah this is consequence of removing object.di - tango own tests still worked because `rt` modules were still present in the import path. Should be quite simple to fix.

**Comment by leandro-lucarella-sociomantic** [comment]
Rebuilding to pick up the new tangort v1.9.0-rc.2 package.

**Comment by leandro-lucarella-sociomantic** [comment]
Green. I'll merge and do a RC for cachalot, then we can create a few PRs in key projects to see if something obvious comes up, and if it doesn't, I would just release the final version.

**Comment by leandro-lucarella-sociomantic** [comment]
* https://github.com/dlang/dmd/pull/8372
* https://github.com/sociomantic-tsunami/tangort/pull/36
* https://github.com/sociomantic-tsunami/d1to2fix/pull/30
* https://github.com/sociomantic-tsunami/ocean/pull/535

**Comment by leandro-lucarella-sociomantic** [comment]
OK, it seems like all is :heavy_check_mark:

**Comment by leandro-lucarella-sociomantic** [comment]
Released v5.0.0. final

**Pull request merged**
