### PR TITLE
Fix typo in build-img description

### PR DESCRIPTION
**Pull request by stefan-koch-sociomantic**
just a simple typo fix.

### CODE REVIEW

**Review by joseph-wakeling-sociomantic — APPROVED** [review]

**Comment by joseph-wakeling-sociomantic** [comment]
Minor suggestion: `Fix typo in build-img description` might give a better sense of the change.

**Review by joseph-wakeling-sociomantic — APPROVED** [review]
Thanks for the commit title fix!

**Comment by joseph-wakeling-sociomantic** [comment]
(would suggest updating PR title accordingly)

**Comment by stefan-koch-sociomantic** [comment]
Thanks for your suggestion @joseph-wakeling-sociomantic

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

**Pull request merged**
