### PR TITLE
Move dlang related repos to dlang docker

### PR DESCRIPTION
**Pull request by stefan-koch-sociomantic**
as per title

### CODE REVIEW

**Comment by stefan-koch-sociomantic** [comment]
@nemanja-boric-sociomantic as I am not a member of sociomatic-tsunami it seems I cannot request a review from you or @leandro-lucarella-sociomantic

**Review by leandro-lucarella-sociomantic — APPROVED** [review]

**Comment by leandro-lucarella-sociomantic** [comment]
This should actually go to v4, because it's in fact a "breaking change" in the sense that if people were getting D tools using the base images, now it won't work.

**Comment by leandro-lucarella-sociomantic** [comment]
Just to make it clear, can you please rebase this PR on top of v4.x.x?

**Comment by stefan-koch-sociomantic** [comment]
@leandro-lucarella-sociomantic rebased.

**Review by leandro-lucarella-sociomantic — APPROVED** [review]

**Pull request merged**
