### PR TITLE
Install hmod in sociomantictsunami/dlang image

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**
hmod is a program for generating the documentation as part of
the build process, so it's now included in the dlang image.

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
Hm, we need to put `hmod` in bintray @leandro-lucarella-sociomantic

**Comment by nemanja-boric-sociomantic** [comment]
I wonder if we could build community-upstream right away (https://github.com/dlang-community/harbored-mod) ?

**Comment by mihails-strasuns-sociomantic** [comment]
It is the same problem as with dstep - we either need to make `beaver bintray upload` part of the upstream repo or maintain the fork with that and packaging scripts.

**Review by leandro-lucarella-sociomantic — COMMENTED** [review]
Yeah, unless there is a package called `hmod` somewhere to be download, we can't really merge this. Blocking.

**Comment by leandro-lucarella-sociomantic** [comment]
> It is the same problem as with dstep - we either need to make beaver bintray upload part of the upstream repo or maintain the fork with that and packaging scripts.

With dlang-community it might be easier to succeed, as we have some maintainers. Specially with `hmod` that was abandoned and we are sort of the *official maintainers* I don't see any limitations to do that, except that we need a new bintray entity (we can't share our sociomantic credentials with the whole dlang-community :).

**Comment by leandro-lucarella-sociomantic** [comment]
Actually.... I think if we encrypt the credentials, they can't be decrypted as only travis have the decryption key, or am I wrong? In any case, @nemanja-boric-sociomantic could you handle this?

**Comment by nemanja-boric-sociomantic** [comment]
But where would be the decryption key stored? Can we make travis use sociomantic's keys for another organization's repo?

**Comment by leandro-lucarella-sociomantic** [comment]
> But where would be the decryption key stored?

Travis handle them AFAIK. I'm talking about https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml and https://docs.travis-ci.com/user/encryption-keys/ (I never read the later, but I guess it has the answers to our questions).

**Comment by leandro-lucarella-sociomantic** [comment]
> Can we make travis use sociomantic's keys for another organization's repo?

Yes, they are just environment variables.

But actually the problem is, if anybody changes the build script to send the plain text value of the env var, it will be leaked, so we can't use our credential in non-socio repos. We'll have to create another org. Or maybe another repo in the sociomantic org with a special user that only have access to that repo.

**Comment by mihails-strasuns-sociomantic** [comment]
Yes, reusing same keys won't work because no matter what you do, any other person with admin access to same repo/organization will be able to leak them and reuse.

Actually, creating dedicated bintray organization for `dlang-community` and sharing access with other maintainers sounds like decent idea. Other may want a place for quick and dirty debian package upload too.

**Comment by leandro-lucarella-sociomantic** [comment]
https://github.com/dlang-community/discussions/issues/25

**Comment by leandro-lucarella-sociomantic** [comment]
I just uploaded a package we did internally, but the version is quite crappy so I've put it in the prerelease component (which so far is not included in the cachalot images, but maybe we should, using the right apt-preferences priority):

https://bintray.com/dlang-community/apt/harbored-mod/v0.2.0%2B58%7Ecb693a7

It would be nice now to make hmod use beaver + cachalot to build the packages and upload them to bintray. @nemanja-boric-sociomantic can you create a bintray account (you can log in using GH credentials) so I can add you to the org so you can make changes in case is necessary.

**Comment by nemanja-boric-sociomantic** [comment]
Sure, I've created the account there.

**Comment by nemanja-boric-sociomantic** [comment]
Part one: https://github.com/dlang-community/harbored-mod/pull/90

**Comment by leandro-lucarella-sociomantic** [comment]
This probably also depends on #42

**Comment by leandro-lucarella-sociomantic** [comment]
#42 merged, and damn, I forgot about this and did an `rc`, I think we can add this for a second `rc`, it shouldn't be a big issue.

**Comment by leandro-lucarella-sociomantic** [comment]
OK, green now.

**Pull request merged**
